665 task endpoint tests
Tracardi/tracardi-api pull request #138
Opened 2022-08-28 17:23 UTC by Mefpef

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 

Tips
----------------

 * Give the same name to the pull request as the name of ticket if possible
 * Make the title in form of: Pull request title (#<issue-id>)
 * Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 * Test your code throughly before PR.

Pull Request title
-------------------

     Write test for tasks API #665 (#665)

Pull Request description
-------------------------

    added test for task_endpoint

----

We need your declaration that your contribution is MIT licensed without it, we can not merge your code.
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT)

2022-08-28 19:48 UTC, DawidekZagajnik commented
I'm taking look at this, once more: something isn't okay with branches - see how many commits you are pushing. Check on it.

2022-08-28 19:54 UTC, DawidekZagajnik requested changes
Pretty good, though you could unify all tests into one function (adding task, checking loading, grouping, then deleting). If you did so, you could use one task: dict variable and instead of 
assert response["ids"] == ["test-id"], you could check for task["id"]. That would make maintenance and modifications easier.

2022-08-28 19:54 UTC, DawidekZagajnik commented on test/api/endpoints/test_task_endpoint.py
> +            "params": {}
you could fill in some params

2022-08-28 19:54 UTC, DawidekZagajnik commented on test/api/endpoints/test_task_endpoint.py
> +            "params": {}
to see if they persist

2022-08-28 19:54 UTC, DawidekZagajnik commented on test/api/endpoints/test_task_endpoint.py
> +        task = {
seems to be responsibility of _add_task. This parameter should be passed there to be consistent

2022-08-30 15:12 UTC, DawidekZagajnik approved these changes
seems ok

2022-08-30 21:37 UTC, atompie approved these changes

2022-08-30 21:38 UTC, merged