docs for contains pattern plugin
Tracardi/tracardi-api pull request #151
Opened 2022-09-17 15:24 UTC by Mefpef

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 

Tips
----------------

 * Give the same name to the pull request as the name of ticket if possible
 * Make the title in form of: Pull request title (#<issue-id>)
 * Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 * Test your code thoroughly before PR.

Pull Request title
-------------------

     #658 contains_pattern_plugin

Pull Request description
-------------------------

    docs for contains pattern plugin

----

We need your declaration that your contribution is MIT licensed without it, we can not merge your code.
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT)

2022-09-18 10:21 UTC, DawidekZagajnik requested changes

2022-09-18 10:21 UTC, DawidekZagajnik commented on manual/en/docs/flow/actions/contains_pattern_action.md
> +Output:
### Output

2022-09-18 10:21 UTC, DawidekZagajnik commented on manual/en/docs/flow/actions/contains_pattern_action.md
> +Plugin outputs the payload on ports TRUE if field contains prefix or FALSE if otherwise.
outputs information about found pattern(s)

2022-09-19 20:31 UTC, atompie approved these changes

2022-09-19 20:31 UTC, merged