User preference endpoints (#704)
Tracardi/tracardi-api pull request #153
Opened 2022-09-21 20:20 UTC by Mefpef

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 

Tips
----------------

 * Give the same name to the pull request as the name of ticket if possible
 * Make the title in form of: Pull request title (#<issue-id>)
 * Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 * Test your code thoroughly before PR.

Pull Request title
-------------------

     User preference endpoints (#704)

Pull Request description
-------------------------

   Filled endpoints:
   GET /user/preferences
   DELETE /user/preference/{key}
   POST /user/prefernece/{key}

----

We need your declaration that your contribution is MIT licensed without it, we can not merge your code.
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT)

2022-09-25 16:39 UTC, DawidekZagajnik requested changes

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
>      Sets user preference.Uses key to set the preference
no idea what it does from this docstring

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +    user_preference = storage.driver.user.preference[key]
storage.driver.user does not seem to have preference attribute with __getitem__ dunder, you get user from args

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +        user_preference.update({key: preference})
update user's preferences in User object that you get from args and then save it

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +    return {"info": "User preference updated"}
return driver response after upserting data

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +    del user.preference[key]
great, now save user using driver

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +    return {"Info": "Preference deleted"}
and return driver response

2022-09-25 16:39 UTC, DawidekZagajnik commented on app/api/user_endpoint.py
> +    return user.preference
seems to work OK

2022-10-04 19:36 UTC, atompie approved these changes

2022-10-04 19:36 UTC, merged